version: '3.8'

volumes:
  pp_volume:

services:
  postgres:
    image: postgres
    container_name: pp_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Password 
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - pp_volume:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U postgres -d postgres'"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s 
  # payment_api:
  #   container_name: pp_api
  #   build: .
  #   command: bundle exec rackup
  #   ports:
  #     - "9292:9292"
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
